blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/smhnaqvi/lahore-software-houses/discussions
    about: Ask questions or discuss the Lahore tech scene here.